from: node:alpine
services:
    - vault:
        from: vault:latest
        env:
            - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:${VAULT_PORT:-8200}
            - VAULT_DEV_ROOT_TOKEN_ID=root
        expose:
            - ${VAULT_PORT:-8200}:${VAULT_PORT:-8200}
env:
    - NODE_ENV=${NODE_ENV:-development}
    - APP_NAME=${APP_NAME:-koa-template}
    - VAULT_APP_NAME=${APP_NAME:-koa-template}
    - APP_PORT_0=${APP_PORT_0:-3000}
    - APP_PORT_1=${APP_PORT_1:-3001}
expose:
    - ${APP_PORT_0:-3000}:${APP_PORT_0:-3000}
    - ${APP_PORT_1:-3001}:${APP_PORT_1:-3001}
before: |
    apk update
    apk add unzip
    export VAULT_VERSION=0.9.3
    export VAULT_SHA256=4ba8b9dafb903d20b4c87e8954015a07a6995f53a9650ac02b39e6cae502645e
    wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
    sha256sum vault_${VAULT_VERSION}_linux_amd64.zip | grep -q "${VAULT_SHA256}  vault_${VAULT_VERSION}_linux_amd64.zip"
    unzip vault_${VAULT_VERSION}_linux_amd64.zip -d /usr/local/bin
    rm vault_${VAULT_VERSION}_linux_amd64.zip
    yarn config set cache-folder ./.yarn-cache
    export VAULT_ADDR=http://$VAULT_PORT_8200_TCP_ADDR:8200
    export VAULT_TOKEN=$VAULT_ENV_VAULT_DEV_ROOT_TOKEN_ID
    sleep 3
tasks:
    env: env | sort
    shell: /bin/sh
    clean: rm -rf node_modules/
    install: yarn install
    build: yarn build
    test: yarn build && yarn mock && yarn test
    lint: yarn lint
    dev: yarn build && yarn mock && yarn dev
    verify: |
        rm -rf node_modules
        yarn
        yarn lint
        yarn test
        yarn build
