version: "3.7"
services:
  nodejs:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./:/koa-template
    environment:
      - NODE_ENV=development
      - APP_NAME=koa-template
      - APP_PORT_0=3000
      - APP_PORT_1=3001
    working_dir: /koa-template
    command: >
      sh -c "yarn &&
      yarn build &&
      yarn dev"
