- name: health-check
  controller: "health-check"
  handler: "ping"
  routes:
    - "/health/ping"
  method:
    - get
  auth:
    sso: false
  proxy:
    enabled: false

- name: sso-logout
  controller: "sso"
  handler: "logout"
  routes:
    - "/sso/logout"
  method:
    - get
  auth:
    sso: false
  proxy:
    enabled: false

- name: sso-code
  controller: "sso"
  handler: "code"
  routes:
    - "/sso/code"
  method:
    - get
  auth:
    sso: false
  proxy:
    enabled: false

- name: sso-status
  controller: "sso"
  handler: "status"
  routes:
    - "/sso/status"
  method:
    - get
  auth:
    sso: false
  proxy:
    enabled: false
