- name: health-check
  controller: health-check
  proxy:
    filter:
      enabled: false
    enabled: false
    redirect: false
    url: ""
  version: v1
  description: ""
  method:
    - get
  route: "/health/ping"
  handler: ping
  auth:
    ldap: false
    sso: false
