- name: health-check
  controller: health-check
  proxy:
    filter:
      enabled: false
      find: ""
      replace: ""
      fields: []
    enabled: false
    redirect: false
    url: ""
  version: v1
  description: ""
  method:
    - get
  route: "/health/ping"
  handler: ping
  auth:
    ldap: false
    sso: false

- name: postman-echo
  controller: ""
  proxy:
    filter:
      enabled: true
      find: "https://localhost"
      replace: "http://localhost:3000"
      fields:
        - url
    enabled: true
    redirect: false
    url: https://postman-echo.com
  description: ""
  method:
    - get
  route: "/get:path*"
  handler: ""
  auth:
    sso: false
